

module.exports = {
  apps: [
    {
      name: "Axle-Production",
      script: "./start/production_start.js",
      instances: 1,
      autorestart: true,
      watch: true,
      max_memory_restart: "4G",
      env: {
        NODE_ENV: "production",
      },
      env_production: {
        NODE_ENV: "production",
      },
    }
  ],
};

// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
